<?php

/**
 * Faq_Model_Doctrine_Faq
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Faq
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Faq_Model_Doctrine_Faq extends Faq_Model_Doctrine_BaseFaq
{
     public static $faqPhotoDimensions = array(
        '126x126' => 'Photo in admin panel',                  // admin
        '122x77' => 'Thumb',
        '245x155' => 'Main photo'
    );
    
    public static function getFaqPhotoDimensions() {
        return self::$faqPhotoDimensions;
    }
    
     public function getId(){
        return $this->_get('id');
    }
    
    public function getMetatagId(){
        return $this->_get('metatag_id');
    }
    
     public function setUp() {
        parent::setUp();
    
        $this->hasOne('Default_Model_Doctrine_Metatag as Metatags', array(
            'local' => 'metatag_id',
            'foregin' => 'id'
        ));
        
         $this->hasOne('Media_Model_Doctrine_Photo as PhotoRoot', array(
            'local' => 'photo_root_id',
            'foreign' => 'id'
        ));
        
        $this->hasMany('Media_Model_Doctrine_Photo as Photos', array(
            'local' => 'photo_root_id',
            'foreign' => 'root_id'
        ));
    }
}