<?php

/**
 * Faq_Model_Doctrine_FaqTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Faq_Model_Doctrine_FaqTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Faq_Model_Doctrine_FaqTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Faq_Model_Doctrine_Faq');
    }
    
     public function getPublishFaqQuery($id, $field = 'id') {
        $q = $this->createQuery('a')
                ->addSelect('a.*')
                ->addSelect('at.*')
                ->addSelect('m.*')
                ->addSelect('mt.*')
                ->leftJoin('a.Translation at')
                ->leftJoin('a.Metatags m')
                 ->leftJoin('m.Translation mt')
                
                ;
        if(is_integer($id)) {
            $q->andWhere('a.' . $field . ' = ?', array($id));
        } elseif(is_array($id) && !empty($id)) {
            $q->andWhere('a.' . $field . ' IN ?', array($id));
        }
        return $q;
    }

    public function getPhotoQuery(Doctrine_Query $q = null) {
        if(null == $q) {
            $q = $this->createQuery('a');
            $q->addSelect('a.*');
        }
        $q->addSelect('pr.*');
        $q->addSelect('p.*');
        $q->leftJoin('a.PhotoRoot pr');
        $q->leftJoin('a.Photos p');
        return $q;
    }
    
    public function getLimitQuery($limit, Doctrine_Query $q = null) {
        if(null == $q) {
            $q = $this->createQuery('a');
            $q->addSelect('a.*');
        }
        $q->limit($limit);
        return $q;
    }
    
    public function getCategoryIdQuery($categoryId = null, Doctrine_Query $q = null) {
        if(null == $q) {
            $q = $this->createQuery('ac');
        }
        $q->addSelect('ac.*');
        $q->leftJoin('a.Category ac');
        if(is_integer($categoryId)) {
            $q->andWhere('ac.id');
        } elseif(is_array($categoryId && !empty($categoryId))) {
            $q->andWhere('ac.id IN ?', array($categoryId));
        }
        return $q;
    }
    
    public function getAllFaqQuery() {
        $q = $this->createQuery('a')
                ->addSelect('a.*')
                ->addSelect('at.*')
                ->addSelect('pr.*')
                ->leftJoin('a.PhotoRoot pr')
                ->leftJoin('a.Translation at');
        return $q;
    }
    
    public function getFaqForSiteMapQuery() {
        $q = $this->createQuery('cat');
        $q->addSelect('cat.*');
        $q->addSelect('pro.*');
        $q->addSelect('tr.*');
        $q->leftJoin('cat.Translation tr');
        $q->leftJoin('cat.Products pro');
        $q->andWhere('pro.status = ?', 1);
        $q->andWhere('pro.availability > ?', 0);
        $q->andWhere('pro.reduced_price = ?', 0);
        return $q;
    }
}