<?php

/**
 * Faq_Model_Doctrine_FaqTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Faq
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Faq_Model_Doctrine_FaqTranslation extends Faq_Model_Doctrine_BaseFaqTranslation
{

}