<?php

/**
 * Faq_Model_Doctrine_FaqTranslationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Faq_Model_Doctrine_FaqTranslationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Faq_Model_Doctrine_FaqTranslationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Faq_Model_Doctrine_FaqTranslation');
    }
}