<div class="wrapper">
	<section class="cols">
		<div class="wrapper pad_bot2">
			<h3><span class="dropcap">1</span>Product name</h3>
			<figure><img src="images/page4_img1.jpg" alt=""></figure>
			<p class="pad_bot1">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
			<a href="#" class="link1">Read More</a>
		</div>
		<div class="wrapper">
			<h3><span class="dropcap">4</span>Product name</h3>
			<figure><img src="images/page4_img2.jpg" alt=""></figure>
			<p class="pad_bot1">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia dese- runt mollit anim id est laborum.</p>
			<a href="#" class="link1">Read More</a>
		</div>
	</section>
	<section class="cols pad_left1">
		<div class="wrapper pad_bot2">
			<h3><span class="dropcap">2</span>Product name</h3>
			<figure><img src="images/page4_img3.jpg" alt=""></figure>
			<p class="pad_bot1">Dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip exea.</p>
			<a href="#" class="link1">Read More</a>
		</div>
		<div class="wrapper">
			<h3><span class="dropcap">5</span>Product name</h3>
			<figure><img src="images/page4_img4.jpg" alt=""></figure>
			<p class="pad_bot1">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.</p>
			<a href="#" class="link1">Read More</a>
		</div>
	</section>
	<section class="cols pad_left1">
		<div class="wrapper pad_bot2">
			<h3><span class="dropcap">3</span>Product name</h3>
			<figure><img src="images/page4_img5.jpg" alt=""></figure>
			<p class="pad_bot1">Commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.</p>
			<a href="#" class="link1">Read More</a>
		</div>
		<div class="wrapper">
			<h3><span class="dropcap">6</span>Product name</h3>
			<figure><img src="images/page4_img6.jpg" alt=""></figure>
			<p class="pad_bot1">Totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
			<a href="#" class="link1">Read More</a>
		</div>
	</section>
</div>
<article class="grid_8">
<h1><?php echo $this->gallery['Translation'][$this->language]['name'] ?></h1>
<?php echo $this->gallery['Translation'][$this->language]['description'] ?>
<?php if($this->gallery->get('PhotoRoot')){ ?>
    <div class="gallery-container gallery-list">

                <div class="gallery-box">
                        <ul>
                            <?php foreach($this->gallery->get('PhotoRoot')->getNode()->getChildren() as $photo): ?>
                                <li>
                                    <a href="/media/photos/<?php echo $photo['offset'] ?>/<?php echo $photo['filename'] ?>" alt="<?php echo $photo['title'] ?>"
                                       data-lightview-group='<?php echo $this->gallery['Translation'][$this->language]['slug'] ?>'
                                       data-lightview-title="<?php echo $photo['title'] ?>"
                                       class='lightview' 
                                       data-lightview-options="
                                           width: 800,
                                           height: 460,
                                           viewport: 'false',
                                         "
                                       >
                                        <img src="/media/photos/<?php echo $photo['offset'] ?>/<?php echo $this->photoDimension; ?>/<?php echo $photo['filename'] ?>" alt="<?php echo $photo['title'] ?>" />
                                    </a>
                                </li>
                                <?php endforeach; ?>
                        </ul>	


                </div>

            </div>
<?php
}
?>
</article>