<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>

<section class="section_offset">
	<main class="container">
	    
	    <div class="col-lg-12 col-md-12 col-sm-12 m_xs_bottom_20 t_align_j">
		<h3 class="color_dark fw_light m_bottom_15 heading_1 t_align_c">
		    <span><?php echo $this->translate('Order created') ?></span>
		</h3>
		<p class="m_bottom_35 heading_2"></p>
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 m_xs_bottom_8 t_align_c ">
            <?php echo $this->translate('Thank you for your order') ?>
			</div>
		</div>
	    </div>
	    
	</main>
			<div class="clearfix"></div>
</section>