    <?php echo $this->render('_menu.phtml') ?>
</div>
<div class="content noTop">
    <div class="blogger">
        <div class="row">
            <div class="col c01">
                        &nbsp;
                    </div>
                    <div class="col bg03 defPad">
                        <div class="row">
                            <div class="col c08">
                                <div class="defPad bg01">
                                    <h1><?php echo $this->article['Translation']['pl']['title']; ?></h1>
                                    <?php if(isset($this->article['PhotoRoot']) && $this->article['PhotoRoot']['filename'] != NULL): ?>
                                        <img src="/media/photos/<?php echo $this->article['PhotoRoot']['offset'] ?>/<?php echo $this->article['PhotoRoot']['filename'] ?>" alt="<?php echo $this->article['PhotoRoot']['alternate_text']; ?>" title="<?php echo $this->article['PhotoRoot']['title']; ?>" class="bloggerThumb"/>
                                    <?php endif; ?>
                                       
                                    <?php echo $this->article['Translation']['pl']['content']; ?>
                                    <div class="clear"></div>
                                </div>
                            </div>
                            <div class="col c02">
                                <div class="defPad fc01 fs12 bg02">
                                    data:  <?php echo $this->article['publish_date']; ?><br/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col c01"></div>
        </div>
        <?php echo $this->article['content']; ?>
       <div class="col c01">
            <br/><br/><br/>
       </div>
    </div>
</div>
<div class="content bottom">