<?php

/**
 * Testimonial_Model_Doctrine_BaseTestimonial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $author_name
 * @property string $city
 * @property clob $description
 * @property boolean $status
 * @property Doctrine_Collection $Translation
 * 
 * @package    Admi
 * @subpackage Testimonial
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Testimonial_Model_Doctrine_BaseTestimonial extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('testimonial_testimonial');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('author_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Testimonial_Model_Doctrine_TestimonialTranslation as Translation', array(
             'local' => 'id',
             'foreign' => 'id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'description',
             ),
             'tableName' => 'testimonial_testimonial_translation',
             'className' => 'TestimonialTranslation',
             ));
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'HasManyRoots' => false,
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($i18n0);
        $this->actAs($nestedset0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}