<?php

/**
 * Testimonial_Model_Doctrine_TestimonialTranslationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Testimonial_Model_Doctrine_TestimonialTranslationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Testimonial_Model_Doctrine_TestimonialTranslationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Testimonial_Model_Doctrine_TestimonialTranslation');
    }
}