<?php

/**
 * Testimonial_Model_Doctrine_TestimonialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Testimonial_Model_Doctrine_TestimonialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Testimonial_Model_Doctrine_TestimonialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Testimonial_Model_Doctrine_Testimonial');
    }
    
    public function getTestimonialQuery() {
        $q = $this->createQuery('t')
                ->addSelect('t.*')
                ->addSelect('tt.*')
                ->leftJoin('t.Translation tt');
        return $q;
    }
}