<?php

/**
 * Order_Model_Doctrine_BaseOrderStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $type
 * @property Doctrine_Collection $Orders
 * @property Order_Model_Doctrine_Delivery $Delivery
 * @property Order_Model_Doctrine_Payment $Payment
 * 
 * @package    Admi
 * @subpackage Order
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Order_Model_Doctrine_BaseOrderStatus extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('order_order_status');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Order_Model_Doctrine_Order as Orders', array(
             'local' => 'id',
             'foreign' => 'order_status_id'));

        $this->hasOne('Order_Model_Doctrine_Delivery as Delivery', array(
             'local' => 'id',
             'foreign' => 'status_id'));

        $this->hasOne('Order_Model_Doctrine_Payment as Payment', array(
             'local' => 'id',
             'foreign' => 'status_id'));

        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($softdelete0);
    }
}