<?php

/**
 * Order_Model_Doctrine_BaseDelivery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $delivery_type_id
 * @property integer $delivery_address_id
 * @property decimal $delivery_cost
 * @property integer $status_id
 * @property Order_Model_Doctrine_OrderStatus $Status
 * @property Order_Model_Doctrine_DeliveryType $DeliveryType
 * @property Order_Model_Doctrine_DeliveryAddress $DeliveryAddress
 * @property Order_Model_Doctrine_Order $Order
 * 
 * @package    Admi
 * @subpackage Order
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Order_Model_Doctrine_BaseDelivery extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('order_delivery');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('delivery_type_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('delivery_address_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('delivery_cost', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('status_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Order_Model_Doctrine_OrderStatus as Status', array(
             'local' => 'status_id',
             'foreign' => 'id'));

        $this->hasOne('Order_Model_Doctrine_DeliveryType as DeliveryType', array(
             'local' => 'delivery_type_id',
             'foreign' => 'id'));

        $this->hasOne('Order_Model_Doctrine_DeliveryAddress as DeliveryAddress', array(
             'local' => 'delivery_address_id',
             'foreign' => 'id'));

        $this->hasOne('Order_Model_Doctrine_Order as Order', array(
             'local' => 'id',
             'foreign' => 'delivery_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}