<?php

/**
 * Order_Model_Doctrine_BaseCoupon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property string $type
 * @property boolean $used
 * @property timestamp $start_validity_date
 * @property timestamp $finish_validity_date
 * @property integer $amount_coupon
 * @property boolean $sent
 * @property integer $order_id
 * @property integer $user_id
 * @property Order_Model_Doctrine_Order $Order
 * 
 * @package    Admi
 * @subpackage Order
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Order_Model_Doctrine_BaseCoupon extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('order_coupon');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('used', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('start_validity_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('finish_validity_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('amount_coupon', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('sent', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('order_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('share_product_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('share_product_email', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Order_Model_Doctrine_Order as Order', array(
             'local' => 'order_id',
             'foreign' => 'id'));

        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($softdelete0);
    }
}