<?php

/**
 * Order_Model_Doctrine_Coupon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Order
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Order_Model_Doctrine_Coupon extends Order_Model_Doctrine_BaseCoupon
{
    public function getId() {
        return $this->_get('id');
    }
    
    public function getCode() {
        return $this->_get('code');
    }
    
    public function setSent($sent = true) {
        $this->_set('sent', $sent);
    }
    
    public function isUsed() {
        return $this->_get('used');
    }
    
    public function getAmount() {
        return $this->_get('amount_coupon');
    }
    
    public function getType() {
        return $this->_get('type');
    }
    
    public function setOrderId($orderId) {
        $this->_set('order_id', $orderId);
    }
    
    public function setUsed($used = true) {
        $this->_set('used', $used);
    }
    
    public function setUserId($userId) {
        $this->_set('user_id', $userId);
    }
    
    public function setUp() {
        $this->hasOne('User_Model_Doctrine_User as User', array(
            'local' => 'user_id',
            'foreign' => 'id'
        ));
        parent::setUp();
    }
}