<?php

/**
 * Order_Model_Doctrine_DeliveryAddress
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Order
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Order_Model_Doctrine_DeliveryAddress extends Order_Model_Doctrine_BaseDeliveryAddress
{
    public function getId() {
        return $this->_get('id');
    }
    
    public function getName() {
        return $this->_get('name');
    }
}