<?php

/**
 * Order_Model_Doctrine_Delivery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Order
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Order_Model_Doctrine_Delivery extends Order_Model_Doctrine_BaseDelivery
{
    public function getId() {
        return $this->_get('id');
    }
    
    public function getStatusId() {
        return $this->_get('status_id');
    }
    
    public function getDeliveryTypeId() {
        return $this->_get('delivery_type_id');
    }
    
    public function getDeliveryCost() {
        return $this->_get('delivery_cost');
    }
}