<?php

/**
 * Order_Model_Doctrine_Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Order
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Order_Model_Doctrine_Item extends Order_Model_Doctrine_BaseItem
{
    public function getId() {
        return $this->_get('id');
    }
    
    public function setVat($vat) {
        $this->_set('vat', $vat);
    }
    
    public function getVat() {
        return $this->_get('vat');
    }
    
    public function setUp() {
        $this->hasOne('Product_Model_Doctrine_Product as Product', array(
            'local' => 'product_id',
            'foreign' => 'id'
        ));
        $this->hasOne('Product_Model_Doctrine_Discount as Discount', array(
            'local' => 'discount_id',
            'foreign' => 'id'
        ));
        parent::setUp();
    }
}