<?php

/**
 * Order_Model_Doctrine_ItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Order_Model_Doctrine_ItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Order_Model_Doctrine_ItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Order_Model_Doctrine_Item');
    }
    
    public function getOrderItemsIdsQuery(){
         $q = $this->createQuery('i')
                ->addSelect('i.id')
                ;
        return $q;
    }
}