<?php

/**
 * Order_Model_Doctrine_OrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Order_Model_Doctrine_OrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Order_Model_Doctrine_OrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Order_Model_Doctrine_Order');
    }
    
    public function getFullOrderQuery() {
        $q = $this->createQuery('o')
                ->addSelect('o.*')
                ->addSelect('u.*')
                ->addSelect('pr.*')
                ->addSelect('i.*')
                ->addSelect('d.*')
                ->addSelect('da.*')
                ->addSelect('prod.*')
                ->addSelect('tr.*')
                ->leftJoin('o.Delivery d')
                ->leftJoin('d.DeliveryAddress da')
                ->leftJoin('o.User u')
                ->leftJoin('u.Profile pr')
                ->leftJoin('o.Items i')
                ->leftJoin('i.Product prod')
                ->leftJoin('prod.Translation tr')
                ;
        return $q;
    }
}