<?php

/**
 * Order_Model_Doctrine_Order
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Order
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Order_Model_Doctrine_Order extends Order_Model_Doctrine_BaseOrder
{
    public function getId() {
        return $this->_get('id');
    }
    
    public function getDeliveryId() {
        return $this->_get('delivery_id');
    }
    
    public function getPaymentId() {
        return $this->_get('payment_id');
    }
    
    public function getUserId() {
        return $this->_get('user_id');
    }
    
    public function getCreatedAt() {
        return $this->_get('created_at');
    }
    
    public function getContactMail() {
        return $this->_get('contact_email');
    }
    
    public function getTotalCost() {
        return $this->_get('total_cost');
    }
    
    public function setTotalCost($totalCost) {
        $this->_set('total_cost', $totalCost);
    }
    
    public function setUp() {
        $this->hasOne('User_Model_Doctrine_User as User', array(
            'local' => 'user_id',
            'foreign' => 'id'
        ));
        parent::setUp();
    }
}