<?php

/**
 * Order_Model_Doctrine_OrderStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Order_Model_Doctrine_OrderStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Order_Model_Doctrine_OrderStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Order_Model_Doctrine_OrderStatus');
    }
    
    public function getOrderStatusQuery() {
        $q = $this->createQuery('os');
        $q->addSelect('os.*');
        return $q;
    }
}