<?php

/**
 * Order_Model_Doctrine_Payment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Order
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Order_Model_Doctrine_Payment extends Order_Model_Doctrine_BasePayment
{
    public function getId() {
        return $this->_get('id');
    }
    
    public function getTs() {
        return $this->_get('ts');
    }
    
    public function getStatus() {
        return $this->_get('status');
    }
    
    public function setStatus($status) {
        $this->_set('status', $status);
    }
    
    public function getStatusId() {
        return $this->_get('status_id');
    }
    
    public function setStatusId($statusId) {
        $this->_set('status_id', $statusId);
    }
    
    public function setErrorStatus($errorStatus) {
        $this->_set('error_status', $errorStatus);
    }
    
    public function getTransId() {
        return $this->_get('trans_id');
    }
    
    public function setTransId($transId) {
        $this->_set('trans_id', $transId);
    }
    
    public function setTs($ts) {
        $this->_set('ts', $ts);
    }
    
    public function getDesc() {
        return $this->_get('desc');
    }
    
    public function setDesc($desc) {
        $this->_set('desc', $desc);
    }
}