<?php

/**
 * Order_Model_Doctrine_PaymentTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Order_Model_Doctrine_PaymentTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Order_Model_Doctrine_PaymentTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Order_Model_Doctrine_PaymentType');
    }
    
    public function getPaymentTypeQuery() {
        $q = $this->createQuery('pt');
        $q->addSelect('pt.*');
        return $q;
    }
}