<?php

/**
 * Order_Model_Doctrine_PaymentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Order_Model_Doctrine_PaymentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Order_Model_Doctrine_PaymentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Order_Model_Doctrine_Payment');
    }
    
    public function getFullPaymentQuery() {
        $q = $this->createQuery('p')
                ->addSelect('p.*')
                ->addSelect('o.*')
                ->addSelect('u.*')
                ->addSelect('d.*')
                ->addSelect('da.*')
                ->leftJoin('p.Order o')
                ->leftJoin('o.User u')
                ->leftJoin('o.Delivery d')
                ->leftJoin('d.DeliveryAddress da')
                ;
        return $q;
    }
}