<button id="back_to_top" class="circle icon_wrap_size_2 color_blue_hover color_grey_light_4 tr_all d_md_none">
	<i class="icon-angle-up fs_large"></i>
</button>

<!--Libs-->
<script src="/assets/plugins/rs-plugin/js/jquery.themepunch.plugins.min.js"></script>
<script src="/assets/plugins/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
<script src="/assets/plugins/jquery.appear.js"></script>
<script src="/assets/plugins/afterresize.min.js"></script>
<script src="/assets/plugins/jquery.easytabs.min.js"></script>
<script src="/assets/plugins/owl-carousel/owl.carousel.min.js"></script>
<script src="/assets/plugins/jackbox/js/jackbox-packed.min.js"></script>
<script src="/assets/plugins/twitter/jquery.tweet.min.js"></script>
<script src="/assets/plugins/flickr.js"></script>
<script src="/assets/plugins/jquery.easing.1.3.js"></script>



<!--Theme Initializer-->
<script src="/assets/js/theme.plugins.js"></script>
<script src="/assets/js/theme.js"></script>