<div id="header" class="clearfix">
    <div class="col-lg-4 col-md-4 col-sm-4">
       
               <div id="logo-wrap"> 
            <div class="logo">
                <a href="/" title="BodyEmpire Cosmetics" target="_blank">
                    <img src="/images/logo_bodyempire.png" alt="BodyEmpire Cosmetics">
                </a>
            </div><!-- end logo -->
        </div><!-- end logo-wrap -->

   
    </div><!-- end col-4 -->               
</div>