<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8">

<?php echo $this->headMeta() ?>
<link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Signika:400,600,300,700&amp;subset=latin,latin-ext" /> 

<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="robots" content="index, follow" />
<meta name="Author" content="Kardi mobile">
<meta name="DC.title" lang="pl" content="<?php echo strip_tags($this->headTitle()) ?>">
<meta name="DC.creator" content="Kardi Mobile">
<meta name="DC.publisher" content="Tomasz Kardas kardi3">
<meta name="DC.contributor" content="kardimobile.pl">
<title>
   <?php if(strlen(strip_tags($this->headTitle()))):
        echo strip_tags($this->headTitle())." - Akademia Piłkarska Świt Krzeszowice";
       else: 
           echo "Akademia Piłkarska Świt Krzeszowice";
           endif; ?>
    
    
</title>


<link rel="stylesheet" href="/assets/css/reset.css" type="text/css" media="all">
<link rel="stylesheet" href="/assets/css/layout.css" type="text/css" media="all">
<link rel="stylesheet" href="/assets/css/style.css" type="text/css" media="all">
<link rel="stylesheet" href="/assets/css/custom.css" type="text/css" media="all">
<!--<link rel="stylesheet" href="/assets/css/bootstrap.min.css" type="text/css" media="all">-->
<link rel="stylesheet" href="/css/print.css" media="print"/>
<link rel="stylesheet" type="text/css" media="screen" href="/plugins/rs-plugin/css/settings.css">
        <link rel="stylesheet" type="text/css" href="/plugins/lightview/css/lightview/lightview.css"/>
<link rel="stylesheet" href="/css/font-awesome.min.css" type="text/css" media="all">
        
<script src="/js/jquery-2.1.0.js"></script>
<script type="text/javascript" src="/assets/js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="/assets/js/tms-0.3.js"></script>
<script type="text/javascript" src="/assets/js/tms_presets.js"></script>
<script type="text/javascript" src="/assets/js/jcarousellite.js"></script>
<script type="text/javascript" src="/assets/js/script.js"></script>
        <script src="/plugins/rs-plugin/js/jquery.themepunch.plugins.min.js"></script>
        <script src="/plugins/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
<script type="text/javascript" src="/plugins/lightview/js/lightview/lightview.js"></script>
        
 
</head>
