<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Dodaj drużyne do turnieju') ?></span>
                </h4>
                
            </div>
            <div class="content clearfix">
                
                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                    
                    
                    
                    <?php echo $this->form->id ?>
                    
                    <?php echo $this->form->name ?>
                    <?php echo $this->form->group_id ?>
                    
                    
                    
                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                        <a href="<?php echo $this->adminUrl('list-team', 'tournament') ?>/tournament_id/<?php echo $this->tournament_id; ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                    </div>
                    
                </form>
            
            </div>
            
        </div>
        
    </div>


</div>