
<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16  icomoon-icon-cart"></span>
                    <span><?php echo $this->translate('Grupy turnieju') ?></span>
                    <div class="box-form right">
                        <a href="<?php echo $this->adminUrl('add-team', 'tournament') ?>/tournament_id/<?php echo $this->tournament_id; ?>" class="btn btn-success btn-mini"><?php echo $this->translate('Add new') ?></a>
                    </div>
               </h4>
            
                
            </div>
            <div class="content clearfix">
                <?php foreach($this->groups as $groupName => $teams): ?>
                <div class="span4">
                <table cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="45%">
                    <thead>
                        <tr>
                            <th colspan="5"><?php echo $groupName; ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($teams as $team): ?>
                        <tr>
                            <td><?php echo $team; ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                </div>
                <?php endforeach; ?>
                
            </div>

        </div>

    </div>
</div>