<div class="container_12 clearfix leading">
    
    <div class="row-fluid">

        <div class="span12">

            <div class="box">
                <?php if($this->form->isErrors()): ?>
                    <div class="message error closeable">
                        <span class="message-close"></span>
                        <h3><?php echo $this->translate('Error') ?>!</h3>
                    </div>
                <?php endif; ?>
                <?php if($this->messages()->count()): ?>
                    <?php echo $this->messages()->render() ?>
                <?php endif; ?>

                <div class="content">
                    <form id="form" class="form" method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">
                        
                        <div class="title">

                            <h4>
                                <span class="icon16 icomoon-icon-pencil"></span>
                                <span><?php echo $this->translate('Check commission for partner') ?>: <?php echo $this->partner['name']; ?></span>
                            </h4>

                        </div>
                        
                        <?php foreach($this->form->getElements() as $element) {
                            if($element->hasErrors()) {
                                $element->setAttrib('class', 'error');
                            }
                        } ?>

                        <?php echo $this->form->start_date->setAttrib('class', 'combiner-picker') ?>
                        <?php echo $this->form->end_date->setAttrib('class', 'combiner-picker') ?>
                        
                        <div class="form-actions">
                             <?php echo $this->form->submit ?>
                             <a href="<?php echo $this->adminUrl('list-partner', 'affilateprogram'); ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
                        </div>  
                    </form>
                    
                    <h3>Wysokość prowizji: <?php echo $this->currency($this->commission); ?>
                </div>

            </div><!-- End .box -->

        </div><!-- End .span12 -->
    
</div>

