<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#partner_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "iDisplayLength": 50,
        "sAjaxSource": "<?php echo $this->adminUrl('list-partner-data', 'affilateprogram') ?>",
        "aaSorting": [[ 2, "desc" ]],
        "aoColumns": [
            null,
            { "bSortable": false, sWidth: '500px' },
            { "bSortable": false, sWidth: '100px' }
        ]
    });
    
    $("#partner_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
});
</script>

<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 cut-icon-list"></span>
                    <span><?php echo $this->translate('Partner list') ?></span>
                    <div class="box-form right">
                        <a href="<?php echo $this->adminUrl('add-partner', 'affilateprogram') ?>" class="btn btn-success btn-mini"><?php echo $this->translate('Add new') ?></a>
                    </div>
                </h4>
            
                
            </div>
          <?php 
         
          ?>
            <div class="content clearfix">
                <table id="partner_table" cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Name') ?></th>
                        <th><?php echo $this->translate('Reference number') ?></th>
                        <th><?php echo $this->translate('Options') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                
            </div>

        </div>

    </div>
</div>