<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#testimonial_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "sAjaxSource": "<?php echo $this->adminUrl('list-testimonial-data', 'testimonial') ?>",
        "aaSorting": [[ 2, "desc" ]],
        "aoColumns": [
            null,
            { sWidth: '200px' },
            { "bSortable": false, sWidth: '50px' },
            { "bSortable": false, sWidth: '50px' },
            { "bSortable": false, sWidth: '50px' }
        ]
    });
    
    $("#testimonial_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
    $("#testimonial_table").delegate("td .move", "click", function(e) {
        e.preventDefault();
        $.ajax({
            url: $(this).attr("href"),
            type: "post",
            dataType: "json",
            data: {format: "json"},
            success: function (resp) {
                $("#testimonial_table").trigger("update");
            }
        });
    });
    
});
</script>
<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 icomoon-icon-list-view"></span>
                    <span><?php echo $this->translate('Testimonials') ?></span>
                    <div class="box-form right">
                        <a href="<?php echo $this->adminUrl('add-testimonial', 'testimonial') ?>" class="btn btn-success btn-mini"><?php echo $this->translate('Add new') ?></a>
                    </div>
                </h4>
                
            </div>
            <div class="content clearfix">
                <table id="testimonial_table" cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Author name') ?></th>
                        <th><?php echo $this->translate('Date') ?></th>
                        <th><?php echo $this->translate('Status') ?></th>
                        <th><?php echo $this->translate('Move') ?></th>
                        <th><?php echo $this->translate('Options') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                
            </div>

        </div><!-- End .box -->

    </div>
</div>