<?php

/**
 * Tournament_Model_Doctrine_BaseTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $slug
 * @property integer $tournament_id
 * @property integer $group_id
 * @property Tournament_Model_Doctrine_Tournament $Tournament
 * @property Doctrine_Collection $Matches
 * @property Doctrine_Collection $Players
 * 
 * @package    Admi
 * @subpackage Tournament
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Tournament_Model_Doctrine_BaseTeam extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('tournament_team');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('tournament_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('group_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tournament_Model_Doctrine_Tournament as Tournament', array(
             'local' => 'tournament_id',
             'foreign' => 'id'));

        $this->hasMany('Tournament_Model_Doctrine_Match as Matches', array(
             'local' => 'id',
             'foreign' => 'team1'));

        $this->hasMany('Tournament_Model_Doctrine_Player as Players', array(
             'local' => 'id',
             'foreign' => 'team_id'));
    }
}