<?php

/**
 * Tournament_Model_Doctrine_BaseMatch
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $team1
 * @property integer $team2
 * @property integer $goal1
 * @property integer $goal2
 * @property integer $tournament_id
 * @property datetime $match_date
 * @property boolean $played
 * @property boolean $group_round
 * @property Tournament_Model_Doctrine_Team $Team1
 * @property Doctrine_Collection $Tournament
 * @property Tournament_Model_Doctrine_Shooter $Shooters
 * 
 * @package    Admi
 * @subpackage Tournament
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Tournament_Model_Doctrine_BaseMatch extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('tournament_match');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('team1', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('team2', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('goal1', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('goal2', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('tournament_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('match_date', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('played', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('group_round', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tournament_Model_Doctrine_Team as Team1', array(
             'local' => 'team1',
             'foreign' => 'id'));

        $this->hasMany('Tournament_Model_Doctrine_Tournament as Tournament', array(
             'local' => 'tournament_id',
             'foreign' => 'id'));

        $this->hasOne('Tournament_Model_Doctrine_Shooter as Shooters', array(
             'local' => 'id',
             'foreign' => 'match_id'));
    }
}