<?php

/**
 * Tournament_Model_Doctrine_Match
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Tournament
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tournament_Model_Doctrine_Match extends Tournament_Model_Doctrine_BaseMatch
{
     public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tournament_Model_Doctrine_Team as Team2', array(
             'local' => 'team2',
             'foreign' => 'id'));

    }
}