<?php

/**
 * Tournament_Model_Doctrine_Shooter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Tournament
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tournament_Model_Doctrine_Shooter extends Tournament_Model_Doctrine_BaseShooter
{

}