<?php

/**
 * Tournament_Model_Doctrine_Team
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Tournament
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tournament_Model_Doctrine_Team extends Tournament_Model_Doctrine_BaseTeam
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tournament_Model_Doctrine_Tournament as Tournament', array(
             'local' => 'tournament_id',
             'foreign' => 'id'));

        $this->hasMany('Tournament_Model_Doctrine_Match as Matches1', array(
             'local' => 'id',
             'foreign' => 'team1'));
        
        $this->hasMany('Tournament_Model_Doctrine_Match as Matches2', array(
             'local' => 'id',
             'foreign' => 'team2'));

        $this->hasMany('Tournament_Model_Doctrine_Player as Players', array(
             'local' => 'id',
             'foreign' => 'team_id'));
    }
}