<!DOCTYPE html>
<html lang="en">
    <head>
        <?php echo $this->render('_head_facebook.phtml') ?>
    </head>
    <body>
        <div class="wrapper">
            <section class="header-wrapper">
                <div class="container">
                    <?php echo $this->render('_topbar_facebook.phtml') ?>
                    <?php echo $this->render('_header_facebook.phtml') ?>
                </div><!-- end container -->
                <div class="shadow"></div>
            </section><!-- end header wrapper -->
            <?php echo $this->layout()->content; ?>
        </div><!-- end wrapper -->
        <div class="dmtop">
            Scroll to Top
        </div><!-- end dmtop -->

      
        <script src="/js/bootstrap.min.js"></script>
        <script src="/js/retina-1.1.0.js"></script>	
        <script src="/js/jetmenu.js"></script>			
        <script src="/js/jquery.unveilEffects.js"></script>
	<script src="/js/jquery.nav.js"></script>	
	<script src="/js/jquery.hoverex.min.js"></script>
	<script src="/js/application.js"></script>
	<!--<script src="js/application.js"></script>-->
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    </body>
</html>
