<script type="text/javascript">
$(document).ready(function() {
    
    var oTable = $("#item_table").dataTable( {
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bPaginate": false,
        "bFilter": false,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": false,
        "bLengthChange": false,

        "sAjaxSource": "<?php echo $this->adminUrl('list-order-item-data', 'order', array('id' => $this->order->getId())) ?>",
        "aaSorting": [[ 2, "desc" ]],
        "aoColumns": [
            null,
            { "bSortable": false, sWidth: '100px' },
            { "bSortable": false, sWidth: '50px' },
            { "bSortable": false, sWidth: '50px' },
            { "bSortable": false, sWidth: '50px' },
        ]
    });
    
    $("#item_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
    var oTable2 = $("#payment_table").dataTable( {
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bPaginate": false,
        "bFilter": false,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": false,
        "bInfo": false,
        "bLengthChange": false,

        "sAjaxSource": "<?php echo $this->adminUrl('payment-order-data', 'order', array('id' => $this->order->getPaymentId())) ?>",
        "aoColumns": [
            null,
            { "bSortable": false, sWidth: '100px' },
        ]
    });
    
    $("#payment_table").bind("update", function(e) {
        oTable2.fnReloadAjax();
    });
    
    var oTable3 = $("#delivery_table").dataTable( {
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bPaginate": false,
        "bFilter": false,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": false,
        "bLengthChange": false,
         "bInfo": false,
        "sAjaxSource": "<?php echo $this->adminUrl('delivery-order-data', 'order', array('id' => $this->order->getDeliveryId())) ?>",
        "aoColumns": [
            null,
            { "bSortable": false, sWidth: '100px' },
        ]
    });
    
    $("#delivery_table").bind("update", function(e) {
        oTable3.fnReloadAjax();
    });
    
//    $("#item_table").delegate("input", "keypress", function(e) {
//        if(e.keyCode == 13) {
//            var itemId;
//            var vat;
//            vat = $(this).val();
//            itemId = $(this).attr("rel");
//            $.ajax({
//                type: "post",
//                dataType: "json",
//                url: "<?php echo $this->adminUrl('change-item-vat', 'order') ?>",
//                data: {format: "json", itemId: itemId, status: "status", vat: vat, newVat: ""},
//                success: function(resp) {
//                    if(resp.status == "success") {
//                        $(this).val(resp.newVat);
//                        alert("Vat has been changed");
//                    }
//                }
//            });
//        }
//    });
    
});
</script>

<div class="row-fluid">
    <div class="span6">
        <div class="box">
            <div class="title">
                <h4>
                    <span class="icon16 icomoon-icon-user-3"></span>
                    <span><?php echo $this->translate('Customer data') ?></span>
                    <div class="box-form right">
                        <?php if ($this->order['invoice_id']): ?>
                            <?php echo $this->translate('Invoice') ?>
                            <a href="<?php echo $this->adminUrl('pdf-invoice', 'order', array('id' => $this->order['id'], 'pdf' => 1)) ?>" class="tip" title="<?php echo $this->translate('PDF') ?>"><span class="icon24 icomoon-icon-file-pdf"></span></a> 
                        <?php endif; ?>
                    </div>   
                </h4>
            </div>
            <div class="content" style="min-height: 162px;">
                <div style="float:left; padding-left: 20px; width: 250px;">
                <?php echo $this->order['User']['first_name'].' '.$this->order['User']['last_name'].'<br/>'; ?>   
                <?php echo $this->order['User']['Profile']['address'].'<br/>'; ?>    
                <?php echo $this->order['User']['Profile']['postal_code'].' '.$this->order['User']['Profile']['city'].'<br/>'; ?>  
                <?php //echo $this->order['User']['Profile']['province'].'<br/>'; ?> 
                <?php echo $this->order['User']['Profile']['country'].'<br/>'; ?> 
                <?php echo $this->order['User']['Profile']['phone']; ?>  
                </div>
                <div style="float:left;">
                    Dane do wysyłki:<br/>
                    <?php if (strlen($this->order['Delivery']['DeliveryAddress'])):
                        echo $this->order['Delivery']['DeliveryAddress']->getName().'<br/>'; 
                        echo $this->order['Delivery']['DeliveryAddress']['address'].'<br/>'; 
                        echo $this->order['Delivery']['DeliveryAddress']['postal_code'].' '.$this->order['Delivery']['DeliveryAddress']['city'].'<br/>'; 
                        echo $this->order['Delivery']['DeliveryAddress']['province'].'<br/>';  
                    else:
                        echo 'takie same';
                    endif; ?>
                </div>
                <div class="clearfix"></div>
                <div style="padding-left: 20px; margin-top: 20px;">
                    <?php if($this->order['User']): ?>
                    E-mail: <?php echo $this->order['User']['email']; ?> <br/>
                    Telefon: <?php echo $this->order['User']['Profile']['phone']; ?> <br/>
                        <?php else: ?>
                    E-mail: <?php echo $this->order['contact_email']; ?> <br/>
                    Telefon: <?php echo $this->order['contact_number']; ?> <br/>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="span6">
        <div class="box">
            <div class="title">
                <h4>
                    <span class="icon16 icomoon-icon-pencil"></span>
                    <span><?php echo $this->translate('Edit order status') ?></span>
                </h4>
            </div>
            <div class="content">
                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                    <?php echo $this->form->order_status_id->setAttribs(array('class' => 'nostyle')) ?>
                    <?php echo $this->form->type->setValue('order') ?>
                    <?php echo $this->form->id ?>

                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                    </div>       
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="box">
            <div class="title">
                <h4>
                    <span class="icon16 icomoon-icon-list-view"></span>
                    <span><?php echo $this->translate('Order items') ?></span>
                </h4> 
            </div>
            <div class="content clearfix">
                <table id="item_table" cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="100%">
                    <form>
                    <thead>
                        <th><?php echo $this->translate('Product name') ?></th>
                        <th><?php echo $this->translate('Price') ?> [zł]</th>
                        <th><?php echo $this->translate('Number') ?></th>
                        <th><?php echo $this->translate('Discount') ?></th>
                        <th><?php echo $this->translate('VAT [%]') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                    </form>
                </table>  
            </div>
            <div class="total">
                <div style="padding-bottom: 10px; font-size: 16px; color: black;">
                    Wartość produktów: <?php echo $this->currency($this->productsWorth); ?> <br/>
                </div>
                <?php if($this->order['Coupon']):
                    $discount = $this->order['Coupon'];
                    ?>
                <div style="padding-bottom: 10px; font-size: 16px; color: black;">
                    Zniżka - <?php
                    if($discount['type']=="percent")
                        echo $discount['amount_coupon']."%";
                    else
                        echo $discount['amount_coupon']." zł";
                    ?>
                </div>
                <?php endif; ?>
                <div style="padding-bottom: 10px; font-size: 16px; color: black;">
                    Koszty wysyłki: <?php echo $this->currency($this->order['Delivery']['DeliveryType']['price']); ?> <br/>
                </div>
                <?php echo $this->translate('Total cost') ?>: <?php echo $this->currency($this->order['total_cost']); ?>
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span6">
        <div class="box">
            <div class="title">
                <h4>
                    <span class="icon16 icomoon-icon-coin"></span>
                    <span><?php echo $this->translate('Payment') ?></span>
                </h4>   
            </div>
            <div class="content clearfix">
                <table id="payment_table" cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Payment method') ?></th>
                        <th><?php echo $this->translate('Status') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table> 
                <?php if ($this->order['payment_id']): ?>
                    <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                        <?php echo $this->form->payment_status_id->setAttribs(array('class' => 'nostyle')) ?>
                        <?php echo $this->form->type->setValue('payment') ?>
                        <?php echo $this->form->id ?>

                        <div class="form-actions">
                            <?php echo $this->form->submit ?>
                        </div>       
                    </form>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="span6">
        <div class="box">
            <div class="title">
                <h4>
                    <span class="icon16 minia-icon-envelope"></span>
                    <span><?php echo $this->translate('Delivery') ?></span>
               </h4>
            </div>
            <div class="content clearfix">
                <table id="delivery_table" cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Delivery method') ?></th>
                        <th><?php echo $this->translate('Status') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                    <?php echo $this->form->delivery_status_id->setAttribs(array('class' => 'nostyle')) ?>
                    <?php echo $this->form->type->setValue('delivery') ?>
                    <?php echo $this->form->id ?>

                    <div class="form-actions">
                        <?php echo $this->form->submit ?>
                    </div>       
                </form>
                <?php if($this->order['Delivery']['delivery_type_id'] == 9): ?>
                    <?php if($this->order['Delivery']['delivery_cost'] == NULL): ?>
                        <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">
                            <?php echo $this->form->delivery_cost ?>
                            <?php echo $this->form->type->setValue('delivery_cost') ?>
                            <?php echo $this->form->id ?>

                            <div class="form-actions">
                                <?php echo $this->form->submit ?>
                            </div>       
                        </form>
                    <?php else: ?>
                        <h3>
                            <span><?php echo $this->translate('Delivery cost') ?>: <?php echo $this->currency($this->order['Delivery']['delivery_cost']); ?></span>
                        </h3> 
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
