<div class="container_12 clearfix leading">
    
    <div class="grid_12">
 
        <div class="box">
        
          <div class="content">
            <form class="form-horizontal" action="<?php echo $this->form->getAction() ?>" method="post" enctype="multipart/form-data">

                <div class="title">

                    <h4>
                        <span class="icon16 icomoon-icon-pencil"></span>
                        <span><?php echo $this->translate('Edit coupon') ?> <?php echo $this->coupon['code']; ?></span>
                    </h4>

                </div>

                <?php echo $this->form->type ?>
                <?php echo $this->form->amount_coupon ?>
                <?php echo $this->form->start_validity_date->setAttrib('class', 'combiner-picker'); ?>
                <?php echo $this->form->finish_validity_date->setAttrib('class', 'combiner-picker'); ?>
                <?php echo $this->form->id ?>
                    
                <div class="form-actions">
                    <?php echo $this->form->submit ?>
                    <a href="<?php echo $this->adminUrl('list-coupon', 'order'); ?>" class="btn"><?php echo $this->translate('Cancel') ?></a>
               </div>       
            </form>
          </div>
        </div>
    </div>
</div>