<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#coupon_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "iDisplayLength": 50,
        "sAjaxSource": "<?php echo $this->adminUrl('list-coupon-data', 'order') ?>",
        "aaSorting": [[ 2, "desc" ]],
        "aoColumns": [
            { "bSortable": false },
            { sWidth: '200px' },
            { sWidth: '150px' },
            { sWidth: '150px' },
            { "bSortable": false, sWidth: '100px' },
            { "bSortable": false, sWidth: '100px' },
            { "bSortable": false, sWidth: '100px' }
        ]
    });
    
    $("#coupon_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
    //$("#category_id").select2();
});
</script>

<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16 entypo-icon-landscape"></span>
                    <span><?php echo $this->translate('Discount coupons') ?></span>
                    <div class="box-form right">
                        <a href="<?php echo $this->adminUrl('add-coupon', 'order') ?>" class="btn btn-success btn-mini"><?php echo $this->translate('Add new') ?></a>
                    </div>
                </h4>
            
                
            </div>
          <?php 
         
          ?>
            <div class="content clearfix">
                <table id="coupon_table" cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('Code') ?></th>
                        <th><?php echo $this->translate('Type') ?></th>
                        <th><?php echo $this->translate('Amount') ?></th>
                        <th><?php echo $this->translate('Valid') ?></th>
                        <th><?php echo $this->translate('Used') ?></th>
                        <th><?php echo $this->translate('Sent') ?></th>
                        <th><?php echo $this->translate('Options') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                
            </div>

        </div>

    </div>
</div>