<script type="text/javascript">
$(document).ready(function() {
    var oTable = $("#order_table").dataTable( {
        "sPaginationType": "full_numbers",
        "oLanguage": {
            "sUrl": "/plugins/tables/dataTables/datatables.polish.txt"
        },
        "bFilter": true,
        "bDestroy": true,
        "bProcessing": true,
        "bServerSide": true,
        "bLengthChange": false,
        "iDisplayLength": 50,
        "sAjaxSource": "<?php echo $this->adminUrl('list-order-data', 'order') ?>",
        "aaSorting": [[ 3, "desc" ]],
        "aoColumns": [
            { sWidth: '50px' },
            null,
            { "bSortable": false, sWidth: '100px' },
            { sWidth: '150px' },
            { "bSortable": false, sWidth: '200px' },
            { "bSortable": false, sWidth: '120px' },
            { "bSortable": false, sWidth: '200px' },
            { "bSortable": false, sWidth: '50' },
            { "bSortable": false, sWidth: '50px' }
        ]
    });
    
    $("#order_table").bind("update", function(e) {
        oTable.fnReloadAjax();
    });
    
    //$("#category_id").select2();
});
</script>

<div class="row-fluid">

    <div class="span12">
        
        <div class="box">
            
            <div class="title">

                <h4>
                    <span class="icon16  brocco-icon-list"></span>
                    <span><?php echo $this->translate('Orders') ?></span>
               </h4>
            
                
            </div>
          <?php 
         
          ?>
            <div class="content clearfix">
                <table id="order_table" cellpadding="0" cellspacing="0" border="0" class=" display table table-bordered" width="100%">
                    <thead>
                        <th><?php echo $this->translate('ID') ?></th>
                        <th><?php echo $this->translate('Client') ?></th>
                        <th><?php echo $this->translate('Total cost') ?></th>
                        <th><?php echo $this->translate('Date') ?></th>
                        <th><?php echo $this->translate('Consignment') ?></th>
                        <th><?php echo $this->translate('Payment method') ?></th>
                        <th><?php echo $this->translate('Status') ?></th>
                        <th><?php echo $this->translate('Invoice') ?></th>
                        <th><?php echo $this->translate('Options') ?></th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                
            </div>

        </div>

    </div>
</div>