<script>
  var map;

      function initialize() {
        map = new google.maps.Map(document.getElementById('googlemaps'), {
          zoom: 8,
          center: new google.maps.LatLng(40,-187.3),
          mapTypeId: google.maps.MapTypeId.ROADMAP
        });
            
    var infowindow = new google.maps.InfoWindow();
            setMarkers(map,infowindow);
 
      }
      
      function setMarkers(map,infowindow){
           $.getJSON( "/en/location/index/json", function( data ) {
          var items = [];
          $.each( data['locationsJson'], function( key, val ) {
      
		      
                            
					// Get center
					var coords = new google.maps.LatLng(
						val['l_lat'],
						val['l_lng']
					);
                                            
                                            
                                            
                                            map.setCenter(coords);
                                        marker = new google.maps.Marker({
                                                position: coords, 
                                                map: map,
                                                content: val['lt_city']
                                        });
                                        
                                     google.maps.event.addListener(marker, 'click', (function(marker) {  
           return function() {  
               infowindow.setContent(marker.content);  
               infowindow.open(map, marker);  
           }  
         })(marker));  
			
                        }
		);
      
  
  });
      }

      google.maps.event.addDomListener(window, 'load', initialize);
		</script>
               
		<div id="googlemaps" class="google-map hidden-xs"></div>
<section class="singleheader-wrap">
    <div class="singleheader">
        <div class="container">
            <div class="col-lg-6 col-sm-6 col-md-6">
                <div class="single-title">
                    <h3><?php echo $this->translate('LOCATIONS');?></h3>
                </div>
            </div>
            
        </div>  
    </div>
</section>
<section class="homecolon">
    <div class="container">
    <div id="content" class="single col-lg-12 col-md-12 col-sm-12">

            <?php foreach($this->locations as $key => $location): ?>
            
            <div class="col-lg-3 col-md-3 col-sm-12">
                <div class=" he-wrap tpl2">
                  
                                <a href="<?php echo $this->url(array('location' => $location['Translation'][$this->language]['slug']), 'domain-location') ?>" title="">
									<h4><?php echo $location['Translation'][$this->language]['title']; ?></h4>
                                </a>
                </div>
            </div>                        

                
            <?php endforeach; ?>
        
    </div><!-- end content -->
            </div><!-- end container -->
</section>