<script>
    $(document).ready(function(){
			var mapMarkers = [{				
				address: "<?php echo $this->location['Translation'][$this->language]['city']; ?>",
				
			}];
			var mapSettings = {
				controls: {
					panControl: true,
					zoomControl: true,
					mapTypeControl: true,
					scaleControl: true,
					streetViewControl: true,
					overviewMapControl: true
				},
				scrollwheel: false,
				markers: mapMarkers,
				zoom: 6
			};
			var map = $("#googlemaps").gMap(mapSettings);
			var mapCenterAt = function(options, e) {
				e.preventDefault();
				$("#googlemaps").gMap("centerAt", options);
			}
                        });
		</script>

		<div id="googlemaps" class="google-map hidden-xs"></div>
<section class="homecolon">
        	<div class="container">
                <div id="content" class="single col-lg-12 col-md-12 col-sm-12">
                    
                    <div class="single col-lg-7 col-md-7 col-sm-7">
                        <h3 class="new-title" style="text-align:left"><?php echo ucfirst($this->location['Translation'][$this->language]['title']); ?></h3>
                        <?php echo $this->location['Translation'][$this->language]['content']; ?>
                    </div>
                    <div class="single col-lg-5 col-md-5 col-sm-5">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        
                        
                        <br /><br />
                        <h3 style="text-align:left;" class="new-title marginB10 marginT10">Contact</h3>
                        <form id="contactform" class="form-horizontal row" method="post" action="<?php echo $this->form->getAction() ?>" >
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <?php echo $this->form->name ?>
                                <?php echo $this->form->email ?>
                           </div>
                           <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <?php echo $this->form->phone ?>
                                <?php echo $this->form->subject ?>
                           </div>
                           <div class="clearfix"></div>
                           <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <?php echo $this->form->message ?>
                           </div>
                            <?php if($this->form->captcha): ?>
                               <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                   <?php echo $this->form->csrf ?>
                                   <div class="controls captcha">
                                       <?php echo $this->form->captcha ?>
                                   </div>
                               </div>
                           <?php endif; ?>
                           <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <?php echo $this->form->submit ?>
                           </div>
                        </form>
                        <br /><br />
                        <h4 style="text-align:left;" class="new-title marginB10 marginT10"><?php echo $this->translate('Our suppliers in region') ;?></h4>
                        <?php echo $this->translate('Currently no suppliers in this region. Use our online shop to order products.'); ?>
                        <div class="clearfix"></div>
                        <br />
                        <div class="col-md-6">
                        <a href="<?php echo $this->url(array('category' => 'rosacea-line'),'domain-i18n:category'); ?>">
                                <img class="img-thumbnail" style="width:100%;" src="/demos/01_menu.png" alt="">
                            </a>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <a href="<?php echo $this->url(array('category' => 'psoriasis-line'),'domain-i18n:category'); ?>">
                                <img class="img-thumbnail" style="width:100%;" src="/demos/02_menu.png" alt="">
                            </a>
                        </div>
                        <div class="clearfix"></div>
                        <br />
                        <div class="col-md-12">
                            <a href="<?php echo $this->url(array('category' => 'collagen-line'),'domain-i18n:category'); ?>">
                                <img class="img-thumbnail" style="width:100%;" src="/demos/03_menu.png" alt="">
                            </a>
                        </div>
                    </div>
                    
                
                </div><!-- end content -->
			</div><!-- end container -->
		</section><!-- end slider products -->
        