<?php

/**
 * Affilateprogram_Model_Doctrine_BasePartner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $reference_number
 * @property decimal $discount
 * @property decimal $comission
 * @property Doctrine_Collection $PartnerOrders
 * 
 * @package    Admi
 * @subpackage Affilateprogram
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Affilateprogram_Model_Doctrine_BasePartner extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('affilateprogram_partner');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('reference_number', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('discount', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('comission', 'decimal', null, array(
             'type' => 'decimal',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Affilateprogram_Model_Doctrine_PartnerOrders as PartnerOrders', array(
             'local' => 'id',
             'foreign' => 'partner_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}