<?php

/**
 * Affilateprogram_Model_Doctrine_PartnerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Affilateprogram_Model_Doctrine_PartnerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Affilateprogram_Model_Doctrine_PartnerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Affilateprogram_Model_Doctrine_Partner');
    }
    
    public function getOrdersForPartnerQuery($partnerId, $values) {
        $q = $this->createQuery('p');
        $q->addSelect('p.*');
        $q->addSelect('po.*');
        $q->addSelect('o.*');
        $q->leftJoin('p.PartnerOrders po');
        $q->leftJoin('po.Order o');
        $q->where('p.id = ?', $partnerId);
        $q->andWhere('(po.created_at >= ? AND po.created_at <= ?)', array($values['start_date'], $values['end_date']));
        return $q;
    }
    
}