<?php

/**
 * Affilateprogram_Model_Doctrine_PartnerOrdersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Affilateprogram_Model_Doctrine_PartnerOrdersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Affilateprogram_Model_Doctrine_PartnerOrdersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Affilateprogram_Model_Doctrine_PartnerOrders');
    }
}