<?php

/**
 * Affilateprogram_Model_Doctrine_PartnerOrders
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Affilateprogram
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Affilateprogram_Model_Doctrine_PartnerOrders extends Affilateprogram_Model_Doctrine_BasePartnerOrders
{
    public function setPartnerId($partnerId) {
        $this->_set('partner_id', $partnerId);
    }
    
    public function setOrderId($orderId) {
        $this->_set('order_id', $orderId);
    }
    
    public function setUp() {
        $this->hasOne('Order_Model_Doctrine_Order as Order', array(
            'local' => 'order_id',
            'foreign' => 'id'
        ));
        parent::setUp();
    }
}