<?php

/**
 * Affilateprogram_Model_Doctrine_Partner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Affilateprogram
 * @author     Andrzej Wilczyński <and.wilczynski@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Affilateprogram_Model_Doctrine_Partner extends Affilateprogram_Model_Doctrine_BasePartner
{
    public function getId() {
        return $this->_get('id');
    }
    
    public function getReferenceNumber() {
        return $this->_get('reference_number');
    }
    
    public function getDiscount() {
        return $this->_get('discount');
    }
    
    public function getCommission() {
        return $this->_get('comission');
    }
}