<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('order_consignment', 'order_consignment_type_id_order_consignment_type_id');
        $this->dropForeignKey('order_item', 'order_item_product_id_product_product_id');
        $this->dropForeignKey('order_order', 'order_order_user_id_user_user_id');
        $this->dropForeignKey('order_payment', 'order_payment_type_id_order_payment_type_id');
        $this->createForeignKey('order_consignment', 'order_consignment_consignment_type_id_order_consignment_type_id', array(
             'name' => 'order_consignment_consignment_type_id_order_consignment_type_id',
             'local' => 'consignment_type_id',
             'foreign' => 'id',
             'foreignTable' => 'order_consignment_type',
             ));
        $this->createForeignKey('order_payment', 'order_payment_payment_type_id_order_payment_type_id', array(
             'name' => 'order_payment_payment_type_id_order_payment_type_id',
             'local' => 'payment_type_id',
             'foreign' => 'id',
             'foreignTable' => 'order_payment_type',
             ));
        $this->addIndex('order_consignment', 'order_consignment_consignment_type_id', array(
             'fields' => 
             array(
              0 => 'consignment_type_id',
             ),
             ));
        $this->addIndex('order_payment', 'order_payment_payment_type_id', array(
             'fields' => 
             array(
              0 => 'payment_type_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('order_consignment', 'order_consignment_type_id_order_consignment_type_id', array(
             'name' => 'order_consignment_type_id_order_consignment_type_id',
             'local' => 'type_id',
             'foreign' => 'id',
             'foreignTable' => 'order_consignment_type',
             ));
        $this->createForeignKey('order_item', 'order_item_product_id_product_product_id', array(
             'name' => 'order_item_product_id_product_product_id',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'product_product',
             ));
        $this->createForeignKey('order_order', 'order_order_user_id_user_user_id', array(
             'name' => 'order_order_user_id_user_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user_user',
             ));
        $this->createForeignKey('order_payment', 'order_payment_type_id_order_payment_type_id', array(
             'name' => 'order_payment_type_id_order_payment_type_id',
             'local' => 'type_id',
             'foreign' => 'id',
             'foreignTable' => 'order_payment_type',
             ));
        $this->dropForeignKey('order_consignment', 'order_consignment_consignment_type_id_order_consignment_type_id');
        $this->dropForeignKey('order_payment', 'order_payment_payment_type_id_order_payment_type_id');
        $this->removeIndex('order_consignment', 'order_consignment_consignment_type_id', array(
             'fields' => 
             array(
              0 => 'consignment_type_id',
             ),
             ));
        $this->removeIndex('order_payment', 'order_payment_payment_type_id', array(
             'fields' => 
             array(
              0 => 'payment_type_id',
             ),
             ));
    }
}