<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('order_order_status', array(
             'id' => 
             array(
              'primary' => '1',
              'autoincrement' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'deleted_at' => 
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->removeColumn('order_order', 'status');
        $this->addColumn('order_order', 'order_status_id', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->dropTable('order_order_status');
        $this->addColumn('order_order', 'status', 'string', '255', array(
             ));
        $this->removeColumn('order_order', 'order_status_id');
    }
}