<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version20 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('order_delivery_address', 'status', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {

    }
}