<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('order_consignment_type', 'description', 'clob', '', array(
             ));
        $this->addColumn('order_payment_type', 'description', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('order_consignment_type', 'description');
        $this->removeColumn('order_payment_type', 'description');
    }
}