<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version14 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('order_delivery_address', array(
             'id' => 
             array(
              'primary' => '1',
              'autoincrement' => '1',
              'type' => 'integer',
              'length' => '4',
             ),
             'status' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'address' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'postal_code' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'city' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'province' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'deleted_at' => 
             array(
              'notnull' => '',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->addColumn('order_delivery', 'delivery_address_id', '', '', array(
             ));
        $this->changeColumn('order_delivery', 'id', 'integer', '4', array(
             'primary' => '1',
             'autoincrement' => '1',
             ));
    }

    public function down()
    {
        $this->dropTable('order_delivery_address');
        $this->removeColumn('order_delivery', 'delivery_address_id');
    }
}