<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('order_consignment', 'type_id');
        $this->removeColumn('order_payment', 'type_id');
        $this->addColumn('order_consignment', 'consignment_type_id', 'integer', '4', array(
             ));
        $this->addColumn('order_payment', 'payment_type_id', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->addColumn('order_consignment', 'type_id', 'integer', '4', array(
             ));
        $this->addColumn('order_payment', 'type_id', 'integer', '4', array(
             ));
        $this->removeColumn('order_consignment', 'consignment_type_id');
        $this->removeColumn('order_payment', 'payment_type_id');
    }
}