<?php

/**
 * Location_Model_Doctrine_CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Location_Model_Doctrine_CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Location_Model_Doctrine_CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Location_Model_Doctrine_Category');
    }
    
    public function getPublishCategoryQuery() {
        $q = $this->createQuery('a')
                ->addSelect('a.*')
                ->addSelect('at.*')
                ->leftJoin('a.Translation at');
               
        return $q;
    }
}