<?php

/**
 * Location_Model_Doctrine_CategoryTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Location
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Location_Model_Doctrine_CategoryTranslation extends Location_Model_Doctrine_BaseCategoryTranslation
{

}