<?php

/**
 * Location_Model_Doctrine_LocationTranslationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Location_Model_Doctrine_LocationTranslationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Location_Model_Doctrine_LocationTranslationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Location_Model_Doctrine_LocationTranslation');
    }
}