<?php

/**
 * Location_Model_Doctrine_LocationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Location_Model_Doctrine_LocationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Location_Model_Doctrine_LocationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Location_Model_Doctrine_Location');
    }
    
    public function getPublishCategoryQuery() {
        $q = $this->createQuery('a')
                ->addSelect('a.*')
                ->addSelect('at.*')
                ->leftJoin('a.Translation at');
               
        return $q;
    }
    
    public function getPublishLocationQuery() {
        $q = $this->createQuery('l')
                ->addSelect('l.*')
                ->addSelect('lt.*')
                ->leftJoin('l.Translation lt');
               
        return $q;
    }
}