<?php

/**
 * Location_Model_Doctrine_Location
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Admi
 * @subpackage Location
 * @author     Michał Folga <michalfolga@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Location_Model_Doctrine_Location extends Location_Model_Doctrine_BaseLocation
{
    public static $locationPhotoDimensions = array(
        '126x126' => 'Photo in admin panel',    
        '220x120' => 'Main photo'
    );
    
    public static function getLocationPhotoDimensions() {
        return self::$locationPhotoDimensions;
    }
    
    public function getId(){
        return $this->_get('id');
    }
    
     public function setUp() {
        parent::setUp();
    
          $this->hasOne('Default_Model_Doctrine_Metatag as Metatags', array(
            'local' => 'metatag_id',
            'foregin' => 'id'
        ));
        
         $this->hasOne('Media_Model_Doctrine_Photo as PhotoRoot', array(
            'local' => 'photo_root_id',
            'foreign' => 'id'
        ));
        
        $this->hasOne('Default_Model_Doctrine_Metatag as Metatags', array(
            'local' => 'metatag_id',
            'foregin' => 'id'
        ));
    }
}